# Generated by Django 3.0.3 on 2020-02-19 01:13
#TODO Write script for reading in degrees
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Planner', '0004_auto_20200218_2002'),
    ]

    operations = [
    ]
