# Generated by Django 3.0.3 on 2020-04-15 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planner', 'prereqwrite'),
    ]

    operations = [
        migrations.AddField(
            model_name='optional_requirement',
            name='majorName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
