# Generated by Django 3.0.3 on 2020-03-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planner', 'missingCourses'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='units',
            field=models.IntegerField(default=120),
            preserve_default=False,
        ),
    ]
