# Generated by Django 3.0.3 on 2020-02-18 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Co',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=9, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('term', models.CharField(blank=True, max_length=5, null=True)),
                ('units', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('coreqs', models.ManyToManyField(related_name='coreqs_rev', through='Planner.Co', to='Planner.Course')),
                ('exclusions', models.ManyToManyField(related_name='_course_exclusions_+', to='Planner.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('units', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('units', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('belongsTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Planner.Plan')),
                ('requires', models.ManyToManyField(to='Planner.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Pre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.IntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_rev', to='Planner.Course')),
                ('req', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Planner.Course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='prereqs',
            field=models.ManyToManyField(related_name='prereqs_rev', through='Planner.Pre', to='Planner.Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='recommended',
            field=models.ManyToManyField(related_name='rec_rev', to='Planner.Course'),
        ),
        migrations.AddField(
            model_name='co',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_rev', to='Planner.Course'),
        ),
        migrations.AddField(
            model_name='co',
            name='req',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Planner.Course'),
        ),
    ]
