# Generated by Django 3.0.3 on 2020-02-19 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Planner', '0005_auto_20200218_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Core_Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('units', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Optional_Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opName', models.CharField(blank=True, max_length=50, null=True)),
                ('opNumber', models.IntegerField()),
                ('letter', models.CharField(max_length=1)),
                ('units', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='plan',
            name='units',
        ),
        migrations.DeleteModel(
            name='Requirement',
        ),
        migrations.AddField(
            model_name='optional_requirement',
            name='belongsTo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Planner.Plan'),
        ),
        migrations.AddField(
            model_name='optional_requirement',
            name='requires',
            field=models.ManyToManyField(blank=True, to='Planner.Course'),
        ),
        migrations.AddField(
            model_name='core_requirement',
            name='belongsTo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Planner.Plan'),
        ),
        migrations.AddField(
            model_name='core_requirement',
            name='requires',
            field=models.ManyToManyField(blank=True, to='Planner.Course'),
        ),
    ]
