# Generated by Django 3.0.3 on 2020-03-30 17:49

from django.db import migrations
from Planner.models import *
import csv

def makeFile(apps, schema_editor):
    file = open('cs_courses.csv','w', encoding="utf-8")
    writer = csv.writer(file)
    courses = Course.objects.all()
    for course in courses:
        if course.description != "NO LONGER OFFERED":
            writer.writerow([course.ID, course.description])
            print("wrote ", course.ID)

    file.close()


class Migration(migrations.Migration):

    dependencies = [
        ('Planner', 'updatedesc'),
    ]

    operations = [migrations.RunPython(makeFile)
    ]
