# Generated by Django 3.0.3 on 2020-03-30 17:59

from django.db import migrations
from Planner.models import *
import csv

def makeFile(apps, schema_editor):
    file = open('cs_edges.csv','w', encoding="utf-8")
    writer = csv.writer(file)
    pres = Pre.objects.all()
    for pre in pres:
        writer.writerow([pre.course.ID, pre.req.ID])
        print("wrote ", pre.course.ID, pre.req.ID)

    file.close()

class Migration(migrations.Migration):

    dependencies = [
        ('Planner', 'empty'),
    ]

    operations = [migrations.RunPython(makeFile)
    ]
