# Generated by Django 3.0.3 on 2020-02-28 05:48

from django.db import migrations
from Planner.models import Course

def removeNone(apps, schema_editor):
    none = Course.objects.get(ID="NONE")
    all = Course.objects.all()
    for c in all:
        c.prereqs.remove(none)
        c.exclusions.remove(none)
        c.recommended.remove(none)
        c.coreqs.remove(none)


class Migration(migrations.Migration):

    dependencies = [
        ('Planner', '0001_plan_units'),
    ]

    operations = [migrations.RunPython(removeNone)
    ]
