# Generated by Django 3.0.3 on 2020-02-28 05:48

from django.db import migrations
from Planner.models import Course


def updateDesc(apps, schema_editor):
    snIn = open("Planner\dataFILES\COMPUTINGLIST.txt",'r',errors = 'replace')
    title = snIn.readline().strip()
    print(title)

    while title != "ENDFILE":
        for i in range(0,7):
            snIn.readline().strip()

        desc = snIn.readline().strip()
        print(desc)
        skip = snIn.readline().strip()
        while len(skip) > 1:
            
            skip = snIn.readline().strip()
        c = Course.objects.get(ID = title)
        c.description = desc
        c.save()
        title= snIn.readline().strip()
        
        print("title",title)

    snIn.close()


    snIn = open("Planner\dataFILES\MATHLIST.txt",'r',errors = 'replace')
    title = snIn.readline().strip()
    print(title)

    while title != "ENDFILE":
        for i in range(0,7):
            snIn.readline().strip()

        desc = snIn.readline().strip()
        print(desc)
        skip = snIn.readline().strip()
        while len(skip) > 1:
            
            skip = snIn.readline().strip()
        c = Course.objects.get(ID = title)
        c.description = desc
        c.save()
        title= snIn.readline().strip()
        
        print("title",title)

    snIn.close()


class Migration(migrations.Migration):

    dependencies = [
        ('Planner', 'removeNoneAgain'),
    ]

    operations = [migrations.RunPython(updateDesc)
    ]
